version: "3.7"
services:
  backend:
    build: .
    restart: always
    entrypoint:
      - /bin/bash
      - ./start-backend.sh
    ports:
      - "3001:3000"
    links:
      - mongo
    depends_on:
      - mongo
    
  mongo:
    image: mongo:5
    restart: always
    volumes:
      - ./home/mongodb:/home/mongodb
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test

    logging:
      driver: "none"

  
             
